name: misb2
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pip
  - cobra=0.29.0
  - pandas=2.2.2
  - jupyterlab=4.1.6
  - networkx=3.3
  - matplotlib=3.8.4
  - scipy=1.13.0
  - pygraphviz=1.12
  - pip:
    - d3flux==0.2.7
