name: misb
channels:
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - python=3.12
  - cobra=0.29.0
  - pandas=2.2.2
  - jupyterlab=4.1.6
  - networkx=3.3
  - matplotlib=3.8.4
  - scipy=1.13.0
  - pygraphviz=1.12
